## Creating a Complete Set of Nutrients for the Consumed Foods

In [123]:
!pip install -r requirements.txt

Requirement already satisfied: CFEDemands>=0.6.3.dev0 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.6.4.dev0)
Requirement already satisfied: ConsumerDemands>=0.4.3.dev0 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.4.3.dev0)
Requirement already satisfied: matplotlib>=3.3.4 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (3.10.1)
Requirement already satisfied: Pint>=0.8.1 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (0.24.4)
Requirement already satisfied: numpy>=1.21.5 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 17)) (2.2.4)
Requirement already satisfied: pandas>=1.3.5 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 23)) (2.2.3)
Requirement already satisfied: plotly>=5.1.0 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 26)) (6.0.1)
Requirement already satisfied: eep153_tools>=0.11 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 28)) (0.12.4)
Requirement already satisfied: python-gnupg in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 29)) (0.5.4)
Requirement already satisfied: fooddatacentral in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 31)) (1.0.10)
Requirement already satisfied: gspread_pandas>=3.3 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 33)) (3.3.0)
Requirement already satisfied: scikit-learn in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 35)) (1.6.0)
Requirement already satisfied: xarray in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 36)) (2025.1.1)
Requirement already satisfied: scipy>=1.7.3 in /srv/conda/lib/python3.11/site-packages (from CFEDemands>=0.6.3.dev0->-r requirements.txt (line 5)) (1.14.1)
Requirement already satisfied: importlib_metadata>=6.7.0 in /srv/conda/lib/python3.11/site-packages (from CFEDemands>=0.6.3.dev0->-r requirements.txt (line 5)) (8.6.1)
Requirement already satisfied: fsspec in /srv/conda/lib/python3.11/site-packages (from CFEDemands>=0.6.3.dev0->-r requirements.txt (line 5)) (2025.3.2)
Requirement already satisfied: contourpy>=1.0.1 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (24.2)
Requirement already satisfied: pillow>=8 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.3.4->-r requirements.txt (line 10)) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.1.0 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.8.1->-r requirements.txt (line 13)) (4.3.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.8.1->-r requirements.txt (line 13)) (4.12.2)
Requirement already satisfied: flexcache>=0.3 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.8.1->-r requirements.txt (line 13)) (0.3)
Requirement already satisfied: flexparser>=0.4 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.8.1->-r requirements.txt (line 13)) (0.4)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/lib/python3.11/site-packages (from pandas>=1.3.5->-r requirements.txt (line 23)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /srv/conda/lib/python3.11/site-packages (from pandas>=1.3.5->-r requirements.txt (line 23)) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in /srv/conda/lib/python3.11/site-packages (from plotly>=5.1.0->-r requirements.txt (line 26)) (1.33.0)
Requirement already satisfied: gspread<6,>=5.0.0 in /srv/conda/lib/python3.11/site-packages (from gspread_pandas>=3.3->-r requirements.txt (line 33)) (5.12.4)
Requirement already satisfied: decorator in /srv/conda/lib/python3.11/site-packages (from gspread_pandas>=3.3->-r requirements.txt (line 33)) (5.1.1)
Requirement already satisfied: google-auth in /srv/conda/lib/python3.11/site-packages (from gspread_pandas>=3.3->-r requirements.txt (line 33)) (2.38.0)
Requirement already satisfied: google-auth-oauthlib in /srv/conda/lib/python3.11/site-packages (from gspread_pandas>=3.3->-r requirements.txt (line 33)) (1.2.1)
Requirement already satisfied: joblib>=1.2.0 in /srv/conda/lib/python3.11/site-packages (from scikit-learn->-r requirements.txt (line 35)) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /srv/conda/lib/python3.11/site-packages (from scikit-learn->-r requirements.txt (line 35)) (3.6.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /srv/conda/lib/python3.11/site-packages (from google-auth->gspread_pandas>=3.3->-r requirements.txt (line 33)) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /srv/conda/lib/python3.11/site-packages (from google-auth->gspread_pandas>=3.3->-r requirements.txt (line 33)) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /srv/conda/lib/python3.11/site-packages (from google-auth->gspread_pandas>=3.3->-r requirements.txt (line 33)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /srv/conda/lib/python3.11/site-packages (from google-auth-oauthlib->gspread_pandas>=3.3->-r requirements.txt (line 33)) (2.0.0)
Requirement already satisfied: zipp>=3.20 in /srv/conda/lib/python3.11/site-packages (from importlib_metadata>=6.7.0->CFEDemands>=0.6.3.dev0->-r requirements.txt (line 5)) (3.21.0)
Requirement already satisfied: six>=1.5 in /srv/conda/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.4->-r requirements.txt (line 10)) (1.17.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /srv/conda/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth->gspread_pandas>=3.3->-r requirements.txt (line 33)) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /srv/conda/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas>=3.3->-r requirements.txt (line 33)) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /srv/conda/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas>=3.3->-r requirements.txt (line 33)) (2.32.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/lib/python3.11/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas>=3.3->-r requirements.txt (line 33)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/lib/python3.11/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas>=3.3->-r requirements.txt (line 33)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/lib/python3.11/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas>=3.3->-r requirements.txt (line 33)) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/lib/python3.11/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas>=3.3->-r requirements.txt (line 33)) (2025.1.31)

In [124]:
Ethiopia_Data = 'https://docs.google.com/spreadsheets/d/1PVqM25qZyDz5K3jsLDu-JgPS5-vmro4wHk8k6OIB9Eo/edit?usp=sharing'

In [125]:
import pandas as pd
import numpy as np
from eep153_tools.sheets import read_sheets

# Change 'Uganda_Data' to key of your own sheet in Sheets, above
x = read_sheets(Ethiopia_Data,sheet='Food Expenditures (2018-19)')
x = x.set_index(['i','t','m','j']).squeeze()

In [126]:
# Now prices
p = read_sheets(Ethiopia_Data,sheet='Food Prices (2018-19)').set_index(['t','m','j','u'])

# Compute medians of prices for particular time, place and unit
p = p.groupby(['t','m','j','u']).median()

# Just keep metric units
p = p.xs('Kg',level="u").squeeze().unstack('j')

# Drop prices for goods we don't have expenditures for
p = p[x.index.levels[-1]].T

# Household characteristics
d = read_sheets(Ethiopia_Data,sheet="Household Characteristics")
d.columns.name = 'k'

# Fill blanks with zeros
d = d.replace(np.nan,0)

# Expenditures x may have duplicate columns
x = x.T.groupby(['i','t','m','j']).sum()
x = x.replace(0,np.nan) # Replace zeros with missing

# Take logs of expenditures; call this y
y = np.log(x)

d.set_index(['i','t','m'],inplace=True)

In [127]:
food_expenditures = read_sheets(Ethiopia_Data,sheet='Food Expenditures (2018-19)')

In [128]:
foodseaten = food_expenditures['j'].unique()
listchat = list(foodseaten)
listchat

['Coffee',
 'Onion',
 'Salt',
 'Shiro',
 'Sugar',
 'Berbere',
 'Kariya',
 'Leafy Greens',
 'Lentils',
 'Oils',
 'Papaya',
 'Potato',
 'Avocado',
 'Bread/biscuit',
 'Goat & mutton meat',
 'Eggs',
 'Pasta/Macaroni',
 'Tea',
 'Tomato',
 'Horsebeans',
 'Wheat',
 'Garlic',
 'Beef',
 'Beer',
 'Maize',
 'Chick Pea',
 'Teff',
 'Soda',
 'Rice',
 'Sorghum',
 'Hops (gesho)',
 'Tella',
 'Poultry',
 'Mango',
 'Banana',
 'Millet',
 'Carrot',
 'Field Pea',
 'Other prepared food',
 'Barley',
 'Mung bean',
 'Milk',
 'Orange',
 'Injera',
 'Vetch',
 'Fenugreek',
 'Other fruit',
 'Linseed',
 'Beetroot',
 'Sesame',
 'Butter/ghee',
 'Honey',
 'Oats',
 'Sweet potato',
 'Sun Flower',
 'Cheese',
 'Ground nuts',
 'Other condiments',
 'Niger Seed',
 'Fish',
 'Other seed',
 'Haricot Beans',
 'Moringa/Shiferaw/Halloka',
 'Chat/Kat',
 'Bula',
 'Other cereal',
 'Other tuber or stem',
 'Other pulse or nut',
 'Kocho',
 'Other vegetable',
 'Godere',
 'Boye/Yam',
 'Cassava']

In [129]:
loadmatched = pd.read_pickle("bestchatmatch.pkl")
pd.set_option('display.max_rows', None)
loadmatched

,ingredient,best_match,justification
0,Coffee,"Coffee, brewed from grounds, prepared with tap...",Exact match for brewed coffee.
1,Onion,"Onions, raw",Exact match for raw onions.
2,Salt,"Salt, table",Exact match for table salt.
3,Shiro,None,"No good match for Shiro, a traditional Ethiopi..."
4,Sugar,"Sugar, white, granulated",Exact match for white granulated sugar.
5,Berbere,None,"No good match for Berbere, a traditional Ethio..."
6,Kariya,None,"No good match for Kariya, potentially a local ..."
7,Leafy Greens,"Spinach, raw",Spinach is a common leafy green.
8,Lentils,"Lentils, raw",Exact match for raw lentils.
9,Oils,"Oil, vegetable, canola or sunflower",General match for vegetable oil.
10,Papaya,"Papayas, raw",Exact match for raw papayas.
11,Potato,"Potatoes, raw, skin",Exact match for raw potatoes.
12,Avocado,"Avocados, raw",Exact match for raw avocados.
13,Bread/biscuit,"Bread, whole-wheat",Bread is a close category match.
14,Goat & mutton meat,"Lamb, raw",Lamb is similar to mutton in category.
15,Eggs,"Egg, whole, raw, fresh",Exact match for fresh eggs.
16,Pasta/Macaroni,"Macaroni, cooked, enriched",Exact match for cooked macaroni.
17,Tea,"Tea, brewed, prepared with tap water",Exact match for brewed tea.
18,Tomato,"Tomatoes, raw",Exact match for raw tomatoes.
19,Horsebeans,None,No good match for horsebeans (broad beans).
20,Wheat,"Wheat, hard white, raw",Exact match for raw wheat.
21,Garlic,"Garlic, raw",Exact match for raw garlic.
22,Beef,"Beef, ground, raw",Exact match in terms of meat type.
23,Beer,"Beer, regular, all",Exact match for regular beer.
24,Maize,"Corn, sweet, yellow, raw",Maize is commonly referred to as corn.
25,Chick Pea,"Chickpeas, raw",Exact match for raw chickpeas.
26,Teff,None,"No good match for Teff, an Ethiopian grain."
27,Soda,"Beverages, carbonated, cola",Soda is a carbonated beverage.
28,Rice,"Rice, white, long-grain, raw, enriched","Exact match for white rice, raw."
29,Sorghum,None,"No good match for sorghum, a cereal grain."
30,Hops (gesho),None,"No good match for gesho, a traditional Ethiopi..."
31,Tella,None,"No good match for Tella, a traditional Ethiopi..."
32,Poultry,"Chicken, broilers or fryers, roasted, meat and...",Chicken is a type of poultry.
33,Mango,"Mangos, raw",Exact match for raw mangoes.
34,Banana,"Bananas, raw",Exact match for raw bananas.
35,Millet,None,"No good match for millet, a small-seeded grain."
36,Carrot,"Carrots, raw",Exact match for raw carrots.
37,Field Pea,None,No good match found for field peas.
38,Other prepared food,"Soup, chicken, low sodium, canned, condensed",Canned soup is a prepared food.
39,Barley,"Barley, pearled, raw",Exact match for pearled barley.
40,Mung bean,"Mung beans, raw",Exact match for raw mung beans.
41,Milk,"Milk, whole, 3.25% milkfat, without added vita...",Exact match for whole milk.
42,Orange,"Oranges, raw, all commercial varieties",Exact match for raw oranges.
43,Injera,None,"No good match for Injera, a traditional Ethiop..."
44,Vetch,None,"No good match for vetch, a type of legume."
45,Fenugreek,None,No good match for fenugreek seeds or leaves.
46,Other fruit,"Fruit salad, (peach and pear and apricot and p...",Fruit salad comprises various fruits.
47,Linseed,None,No good match for linseed (flaxseed).
48,Beetroot,"Beets, raw",Exact match for raw beets.
49,Sesame,"Seeds, sesame seeds, whole, roasted and toasted",Closest match for sesame seeds.
50,Butter/ghee,"Butter, salted",Butter is closely related to ghee as a dairy f...
51,Honey,Honey,Exact match for honey.
52,Oats,Oats,Exact match for oats.
53,Sweet potato,"Sweet potatoes, raw, unprepared",Exact match for raw sweet potatoes.
54,Sun Flower,"Sunflower seeds, dry roasted, without salt",Sunflower refers to sunflower seeds.
55,Cheese,"Cheese, cheddar",Cheddar is a common type of cheese.
56,Ground nuts,"Peanuts, raw",Ground nuts generally refer to peanuts.
57,Other condiments,"Spices, chili powder",Chili powder is a type of condiment.
58,Niger Seed,None,"No good match for niger seed, typically used f..."
59,Fish,"Fish, salmon, pink, raw",Salmon is a common type of fish.
60,Other seed,"Seeds, flaxseed",Flaxseed is a type of seed.
61,Haricot Beans,"Beans, navy, mature seeds, raw",Haricot beans are also known as navy beans.
62,Moringa/Shiferaw/Halloka,None,"No good match for Moringa, Shiferaw, or Halloka."
63,Chat/Kat,None,"No good match for Chat or Kat, a stimulant plant."
64,Bula,None,"No good match for Bula, potentially a local term."
65,Other cereal,"Cereal, bran flakes",Bran flakes represent a type of cereal.
66,Other tuber or stem,"Celeriac, raw",Celeriac is an uncommon tuber-like plant.
67,Other pulse or nut,"Lentils, raw",Lentils are a type of pulse.
68,Kocho,None,"No good match for Kocho, a traditional Ethiopi..."
69,Other vegetable,"Vegetables, mixed, canned, drained solids",Mixed vegetables incorporate a variety of vege...
70,Godere,None,"No good match for Godere, a type of tuber."
71,Boye/Yam,"Yam, raw",Exact match for raw yams.
72,Cassava,"Cassava, raw",Exact match for raw cassava.

In [130]:
matched_ing = read_sheets(Ethiopia_Data,sheet='FCT Sorted')

In [131]:
print(matched_ing.shape[0], len(read_sheets(Ethiopia_Data,sheet='Food Expenditures (2018-19)')['j'].unique()))

47 73

In [132]:
ranked_expenditures = food_expenditures.groupby('j')['Expenditure'].sum().sort_values(ascending = False)
ranked_expendituresdf = pd.DataFrame(data = ranked_expenditures)
#create cutoff
ranked_expendituresdf['% Total Exp'] = (ranked_expendituresdf['Expenditure']/ ranked_expendituresdf['Expenditure'].sum()) * 100
pd.set_option('display.max_rows', None)
ranked_expendituresdf

                          Expenditure  % Total Exp
j
Teff                        372262.64     9.464053
Oils                        263073.00     6.688119
Beef                        214032.00     5.441347
Chat/Kat                    213383.00     5.424847
Onion                       196688.00     5.000409
Goat & mutton meat          166190.00     4.225057
Coffee                      163414.00     4.154483
Berbere                     154324.00     3.923387
Sugar                       147260.00     3.743799
Maize                       142614.64     3.625700
Rice                        128899.50     3.277019
Wheat                       128603.45     3.269492
Pasta/Macaroni              111955.00     2.846238
Tomato                      107308.00     2.728097
Bread/biscuit               104511.00     2.656989
Milk                        104304.00     2.651726
Injera                      102371.00     2.602583
Potato                       91536.00     2.327125
Lentils                      85598.00     2.176162
Shiro                        81285.00     2.066513
Sorghum                      58041.21     1.475585
Garlic                       57442.00     1.460351
Soda                         52734.00     1.340659
Leafy Greens                 49082.00     1.247814
Banana                       47223.00     1.200553
Beer                         46622.00     1.185274
Eggs                         44097.00     1.121080
Butter/ghee                  40524.00     1.030244
Tea                          40502.00     1.029684
Salt                         37666.00     0.957585
Chick Pea                    36370.00     0.924636
Kariya                       32802.00     0.833927
Horsebeans                   30622.00     0.778505
Poultry                      22970.00     0.583968
Orange                       21841.00     0.555265
Barley                       21452.25     0.545382
Mango                        20986.00     0.533528
Field Pea                    20024.00     0.509071
Other prepared food          16297.00     0.414319
Carrot                       15691.00     0.398913
Fenugreek                    13758.00     0.349770
Honey                        11146.00     0.283365
Fish                         10506.00     0.267095
Avocado                      10272.00     0.261146
Haricot Beans                 9827.00     0.249832
Kocho                         9644.00     0.245180
Beetroot                      8938.00     0.227231
Vetch                         8621.00     0.219172
Millet                        7587.00     0.192885
Oats                          6414.25     0.163070
Ground nuts                   5900.00     0.149996
Tella                         5416.00     0.137691
Cheese                        4770.00     0.121268
Papaya                        4562.00     0.115980
Linseed                       3563.00     0.090582
Bula                          3338.00     0.084862
Hops (gesho)                  3197.00     0.081277
Sesame                        2491.00     0.063329
Sun Flower                    1985.00     0.050465
Niger Seed                    1687.00     0.042889
Sweet potato                  1654.00     0.042050
Moringa/Shiferaw/Halloka      1238.00     0.031474
Other vegetable               1230.00     0.031270
Other condiments               853.00     0.021686
Other seed                     795.00     0.020211
Other fruit                    509.00     0.012940
Godere                         193.00     0.004907
Other cereal                   159.00     0.004042
Cassava                        155.00     0.003941
Other pulse or nut             139.00     0.003534
Boye/Yam                       130.00     0.003305
Other tuber or stem            105.00     0.002669
Mung bean                       55.00     0.001398

In [133]:
pd.reset_option('display.max_rows')

## Setting a cutoff
Our determined cutoff is 0.1% of total spend. This means that we will not proceed with manual search and inclusion of any items that are not included below the cutoff in our matched_ing data from our sheet.

In [134]:
#Left to match
fullexpenddf = read_sheets(Ethiopia_Data,sheet='Food Expenditures (2018-19)')
filtered_df = fullexpenddf[~fullexpenddf['j'].isin(matched_ing['index'])]
to_match_manually =filtered_df['j'].unique()
print(len(to_match_manually), to_match_manually)

27 ['Shiro' 'Kariya' 'Lentils' 'Tomato' 'Horsebeans' 'Wheat' 'Chick Pea'
 'Hops (gesho)' 'Poultry' 'Millet' 'Carrot' 'Field Pea'
 'Other prepared food' 'Mung bean' 'Vetch' 'Other fruit' 'Sesame'
 'Sun Flower' 'Other condiments' 'Niger Seed' 'Other seed' 'Haricot Beans'
 'Chat/Kat' 'Bula' 'Other tuber or stem' 'Kocho' 'Godere']

In [135]:
# left to manually match after 0.1% cutoff
items_below_cutoff = ranked_expendituresdf[ranked_expendituresdf['% Total Exp'] < 0.1].index
new_list_of_search_items = to_match_manually[~pd.Series(to_match_manually).isin(items_below_cutoff)]
print(items_below_cutoff,new_list_of_search_items, f"\n \n Number of remaining items: {len(new_list_of_search_items)}")

Index(['Linseed', 'Bula', 'Hops (gesho)', 'Sesame', 'Sun Flower', 'Niger Seed',
       'Sweet potato', 'Moringa/Shiferaw/Halloka', 'Other vegetable',
       'Other condiments', 'Other seed', 'Other fruit', 'Godere',
       'Other cereal', 'Cassava', 'Other pulse or nut', 'Boye/Yam',
       'Other tuber or stem', 'Mung bean'],
      dtype='object', name='j') ['Shiro' 'Kariya' 'Lentils' 'Tomato' 'Horsebeans' 'Wheat' 'Chick Pea'
 'Poultry' 'Millet' 'Carrot' 'Field Pea' 'Other prepared food' 'Vetch'
 'Haricot Beans' 'Chat/Kat' 'Kocho']

 Number of remaining items: 16

## beginning the manual search

In [136]:
print(new_list_of_search_items)

['Shiro' 'Kariya' 'Lentils' 'Tomato' 'Horsebeans' 'Wheat' 'Chick Pea'
 'Poultry' 'Millet' 'Carrot' 'Field Pea' 'Other prepared food' 'Vetch'
 'Haricot Beans' 'Chat/Kat' 'Kocho']

In [137]:
dict = {'Shiro': 'addmanuallyfromdoc', 'Kariya': 'addmanuallyfromdoc', 'Lentils': 2644283,  'Tomato': 1999634,  'Horsebeans': 'Manual, use favabeans as search', 'Wheat': 790085, 'Chick Pea': 2644282,
        'Poultry' 'Millet': 2512379,  'Carrot': 2258586,  'Field Pea': 2644291,  'Other prepared food': 'Too vague, dropping', 'Vetch': 'addmanuallyfromdoc', 
 'Haricot Beans': 747441, 'Chat/Kat': 'dropping, this is a narcotic known as Khat. Has some nutritional value but does not contribute meaningfully to nutritional outcomes',
        'Kocho': 'addmanuallyfromdoc'
}
dfmanualitems = pd.DataFrame(list(dict.items()), 
                  columns=['ingredient', 'FDC code or source'])

dfmanualitems

             ingredient                                 FDC code or source
0                 Shiro                                 addmanuallyfromdoc
1                Kariya                                 addmanuallyfromdoc
2               Lentils                                            2644283
3                Tomato                                            1999634
4            Horsebeans                    Manual, use favabeans as search
5                 Wheat                                             790085
6             Chick Pea                                            2644282
7         PoultryMillet                                            2512379
8                Carrot                                            2258586
9             Field Pea                                            2644291
10  Other prepared food                                Too vague, dropping
11                Vetch                                 addmanuallyfromdoc
12        Haricot Beans                                             747441
13             Chat/Kat  dropping, this is a narcotic known as Khat. Ha...
14                Kocho                                 addmanuallyfromdoc

**What nutrients do we care about?**

In [138]:
nutrients_collected = list(matched_ing.columns[1:])
print(nutrients_collected)

['Energy', 'Protein', 'Vitamin A', 'Vitamin D', 'Vitamin E', 'Vitamin C', 'Vitamin B-6', 'Vitamin B-12', 'Calcium', 'Magnesium', 'Iron', 'Zinc', 'Fiber', 'Folate', 'Carbohydrate', 'Niacin', 'Phosphorus', 'Potassium', 'Riboflavin', 'Thiamin', 'Vitamin K']

# Finding nutrition for the rest

##### I used all of the above ingredients as search terms in the FDC database to try to find search codes

In [139]:
data_url = "https://docs.google.com/spreadsheets/d/1xqixhrAoDq9rWJf_FC3Y2eXdd010DTLPCS7JJMCfwP8/edit?usp=sharing"
nutrients = read_sheets(data_url, sheet="nutrients")

In [140]:
apikey = "LUJvyyWCR8JkuTS6nSLkEdtiC70cbEfD7TCQbvab"

In [141]:
import fooddatacentral as fdc
import warnings

In [169]:
def get_nutrients(FDC):
    food_nutrients = fdc.nutrients(apikey,FDC)
    if food_nutrients is None:
        return f'no response for {FDC}'
    q = food_nutrients.Quantity
    if "Energy" in q:
        # convert from kJ to kcal ugh
        energy_kcal = q["Energy"] / 4.184
        q["Energy"] = energy_kcal
    return pd.Series(q)

In [172]:
#test
get_nutrients(790646)

/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal

Proximates                              0.000000
Water                                  90.100000
Energy                                 38.240918
Protein                                 0.830000
Total lipid (fat)                       0.050000
Ash                                     0.410000
Carbohydrates                           0.000000
Carbohydrate, by difference             8.610000
Fiber, total dietary                    1.900000
Total dietary fiber (AOAC 2011.25)      2.710000
Sugars, Total                           5.820000
Sucrose                                 1.600000
Glucose                                 2.310000
Fructose                                1.910000
Lactose                                 0.000000
Maltose                                 0.000000
Minerals                                0.000000
Calcium, Ca                            15.000000
Iron, Fe                                0.280000
Magnesium, Mg                           9.000000
Phosphorus, P                          34.000000
Potassium, K                          182.000000
Sodium, Na                              1.000000
Zinc, Zn                                0.200000
Copper, Cu                              0.035000
Manganese, Mn                           0.144000
Iodine, I                               0.000000
Selenium, Se                            0.000000
Vitamins and Other Components           0.000000
Vitamin C, total ascorbic acid          8.200000
Biotin                                  0.000000
Name: Quantity, dtype: float64

In [2]:
def get_preferred_column(candidates, available_columns):
    """
    Returns the first candidate from 'candidates' that exists
    in 'available_columns'. Otherwise returns None.
    """
    for candidate in candidates:
        if candidate in available_columns:
            return candidate
    return None
def select_nutrient_value(row, candidate_list):
    for candidate in candidate_list:
        if candidate in row and pd.notna(row[candidate]):
            return row[candidate]
    return np.nan

def createnutritiondfupdated(fdcids):
    """
    Given a list of FDC IDs, build a DataFrame containing a fixed
    set of nutrients. For nutrients (like Energy) with multiple potential keys,
    select the first available key per row.
    """
    # Gather nutrient data for each FDC ID.
    rows = []
    for fdc_id in fdcids:
        row_series = get_nutrients(fdc_id)
        row_df = pd.DataFrame([row_series])
        # Save the FDC_ID for reference.
        row_df["FDC_ID"] = fdc_id
        rows.append(row_df)
    outputdf = pd.concat(rows, ignore_index=True)
    print("Raw nutrient data:")
    #print(outputdf)
    
    # Define the nutrients you want in the output.
    selected_items = [
        'Energy', 'Protein', 'Vitamin A', 'Vitamin D', 'Vitamin E', 'Vitamin C',
        'Vitamin B-6', 'Vitamin B-12', 'Calcium', 'Magnesium', 'Iron', 'Zinc',
        'Fiber', 'Folate', 'Carbohydrate', 'Niacin', 'Phosphorus', 'Potassium',
        'Riboflavin', 'Thiamin', 'Vitamin K'
    ]
    
    # Map each nutrient to a list of possible keys in order of preference.
    priority_map = {
        'Energy': [
            "Energy",
            "Energy (Atwater Specific Factors)",
            "Energy (Atwater General Factors)"
        ],
        'Protein': ["Protein"],
        'Vitamin A': ["Vitamin A, RAE"],
        'Vitamin C': ["Vitamin C, total ascorbic acid"],
        'Vitamin B-6': ["Vitamin B-6"],
        'Calcium': ["Calcium, Ca"],
        'Magnesium': ["Magnesium, Mg"],
        'Iron': ["Iron, Fe"],
        'Zinc': ["Zinc, Zn"],
        'Fiber': ["Fiber, total dietary"],
        'Folate': ["Folate, total"],
        'Carbohydrate': ["Carbohydrates"],
        'Niacin': ["Niacin"],
        'Phosphorus': ["Phosphorus, P"],
        'Potassium': ["Potassium, K"],
        'Riboflavin': ["Riboflavin"],
        'Thiamin': ["Thiamin"],
        # If you later decide on candidate keys for Vitamin D, Vitamin E, Vitamin B-12, Vitamin K, add them here.
    }
    
    # Build the final DataFrame.
    final_data = pd.DataFrame()
    final_data["FDC_ID"] = outputdf["FDC_ID"]
    
    for nutrient in selected_items:
        if nutrient in priority_map:
            candidate_list = priority_map[nutrient]
            final_data[nutrient] = outputdf.apply(
                lambda row: select_nutrient_value(row, candidate_list), axis=1
            )
        else:
            final_data[nutrient] = np.nan

    final_columns = ["FDC_ID"] + selected_items
    df_final = final_data[final_columns]
    
    return df_final.reset_index(drop=True)

In [3]:
createnutritiondfupdated(2644283)

TypeError: 'int' object is not iterable

In [145]:
inputs = [2644283, 1999634, 790085, 2644282, 2512379, 2258586]

In [146]:
get_nutrients(2644283)

Proximates                             0.00000
Water                                  9.45100
Energy (Atwater General Factors)     360.28500
Energy (Atwater Specific Factors)    350.93280
Nitrogen                               3.77100
Protein                               23.56875
Total lipid (fat)                      1.92500
Ash                                    2.88400
Carbohydrates                          0.00000
Carbohydrate, by difference           62.17125
Starch                                37.13000
Minerals                               0.00000
Calcium, Ca                           61.85000
Iron, Fe                               7.15800
Magnesium, Mg                        106.70000
Phosphorus, P                        373.60000
Potassium, K                         948.90000
Sodium, Na                             0.00000
Zinc, Zn                               3.86300
Copper, Cu                             0.83760
Manganese, Mn                          1.56900
Name: Quantity, dtype: float64

In [147]:
for i in inputs:
    print(get_nutrients(i))

Proximates                             0.00000
Water                                  9.45100
Energy (Atwater General Factors)     360.28500
Energy (Atwater Specific Factors)    350.93280
Nitrogen                               3.77100
Protein                               23.56875
Total lipid (fat)                      1.92500
Ash                                    2.88400
Carbohydrates                          0.00000
Carbohydrate, by difference           62.17125
Starch                                37.13000
Minerals                               0.00000
Calcium, Ca                           61.85000
Iron, Fe                               7.15800
Magnesium, Mg                        106.70000
Phosphorus, P                        373.60000
Potassium, K                         948.90000
Sodium, Na                             0.00000
Zinc, Zn                               3.86300
Copper, Cu                             0.83760
Manganese, Mn                          1.56900
Name: Quantity, dtype: float64
Proximates                              0.000000
Water                                  94.730000
Energy (Atwater General Factors)       21.957400
Energy (Atwater Specific Factors)      18.954361
Nitrogen                                0.111300
Protein                                 0.695625
Total lipid (fat)                       0.425000
Ash                                     0.311900
Carbohydrates                           0.000000
Carbohydrate, by difference             3.837475
Fiber, total dietary                    0.970600
Minerals                                0.000000
Calcium, Ca                             9.963000
Iron, Fe                                0.103100
Magnesium, Mg                           8.089000
Phosphorus, P                          19.090000
Potassium, K                          192.800000
Sodium, Na                              0.000000
Zinc, Zn                                0.082450
Copper, Cu                              0.031980
Manganese, Mn                           0.086900
Selenium, Se                            0.000000
Vitamins and Other Components           0.000000
Vitamin C, total ascorbic acid         17.750000
Thiamin                                 0.055750
Riboflavin                              0.000000
Niacin                                  0.533100
Vitamin B-6                             0.078940
Biotin                                  0.468800
Folate, total                           9.994000
Vitamin A, RAE                         23.900000
Carotene, beta                        275.500000
Carotene, alpha                         0.875000
Carotene, gamma                         2.125000
Cryptoxanthin, beta                    19.060000
Cryptoxanthin, alpha                    9.625000
Lycopene                             2863.000000
Lutein + zeaxanthin                    56.000000
cis-Lutein/Zeaxanthin                   0.000000
Lutein                                 56.000000
Zeaxanthin                              0.000000
Name: Quantity, dtype: float64
Proximates                          0.000
Water                               9.440
Energy                           1550.000
Nitrogen                            2.410
Protein                            15.100
Total lipid (fat)                   2.730
Ash                                 1.560
Carbohydrates                       0.000
Carbohydrate, by difference        71.200
Fiber, total dietary               10.600
Minerals                            0.000
Calcium, Ca                        38.000
Iron, Fe                            3.860
Magnesium, Mg                     136.000
Phosphorus, P                     352.000
Potassium, K                      376.000
Sodium, Na                          3.000
Zinc, Zn                            3.240
Copper, Cu                          0.452
Manganese, Mn                       3.560
Selenium, Se                       23.600
Molybdenum, Mo                     58.500
Vitamins and Other Components       0.000
Thiamin                             0.504
Riboflavin                          0.128
Niacin                              5.550
Vitamin B-6                         0.268
Folate, total                      39.000
Name: Quantity, dtype: float64
Proximates                              0.00000
Water                                   8.77400
Energy (Atwater General Factors)      382.99800
Energy (Atwater Specific Factors)     371.99469
Nitrogen                                3.40400
Protein                                21.27500
Total lipid (fat)                       6.27400
Ash                                     3.31900
Carbohydrates                           0.00000
Carbohydrate, by difference            60.35800
Starch                                 34.14000
Minerals                                0.00000
Calcium, Ca                           111.10000
Iron, Fe                                5.09400
Magnesium, Mg                         134.80000
Phosphorus, P                         353.10000
Potassium, K                         1074.00000
Sodium, Na                              8.77900
Zinc, Zn                                3.12400
Copper, Cu                              0.80410
Manganese, Mn                           3.58100
Name: Quantity, dtype: float64
Proximates                                       0.000000
Water                                           10.210000
Energy (Atwater General Factors)               375.618000
Energy (Atwater Specific Factors)              380.606497
Nitrogen                                         1.719000
Protein                                         10.021770
Total lipid (fat)                                4.194000
Ash                                              1.128000
Carbohydrates                                    0.000000
Carbohydrate, by difference                     74.446230
Fiber, total dietary                             2.619000
Total dietary fiber (AOAC 2011.25)               3.326000
High Molecular Weight Dietary Fiber (HMWDF)      2.729000
Low Molecular Weight Dietary Fiber (LMWDF)       0.000000
Beta-glucan                                      0.000000
Starch                                          67.060000
Minerals                                         0.000000
Calcium, Ca                                      9.105000
Iron, Fe                                         2.534000
Magnesium, Mg                                  105.500000
Phosphorus, P                                  257.900000
Potassium, K                                   214.100000
Sodium, Na                                       0.000000
Zinc, Zn                                         2.258000
Copper, Cu                                       0.488300
Manganese, Mn                                    0.923900
Selenium, Se                                    23.100000
Molybdenum, Mo                                  29.540000
Vitamins and Other Components                    0.000000
Thiamin                                          0.411300
Riboflavin                                       0.136300
Niacin                                           4.860000
Vitamin B-6                                      0.191800
Biotin                                          11.430000
Name: Quantity, dtype: float64
Proximates                             0.000000
Water                                 87.720000
Energy (Atwater General Factors)      47.990600
Energy (Atwater Specific Factors)     44.978589
Nitrogen                               0.150600
Protein                                0.941250
Total lipid (fat)                      0.350600
Ash                                    0.720600
Carbohydrates                          0.000000
Carbohydrate, by difference           10.267550
Fiber, total dietary                   3.095000
Minerals                               0.000000
Calcium, Ca                           30.480000
Iron, Fe                               0.150400
Magnesium, Mg                         12.450000
Phosphorus, P                         39.810000
Potassium, K                         279.600000
Sodium, Na                            86.650000
Zinc, Zn                               0.236400
Copper, Cu                             0.061480
Manganese, Mn                          0.130100
Selenium, Se                           0.000000
Vitamins and Other Components          0.000000
Thiamin                                0.065000
Riboflavin                             0.095000
Niacin                                 1.406000
Vitamin B-6                            0.145600
Biotin                                 2.220000
Folate, total                         37.060000
Name: Quantity, dtype: float64

In [148]:
inputstotal = read_sheets('https://docs.google.com/spreadsheets/d/1PVqM25qZyDz5K3jsLDu-JgPS5-vmro4wHk8k6OIB9Eo/edit?usp=sharing', sheet = 'idmappings')
inputstotal

             Food Items  Expenditure  % Total Exp FDC ID (blank if manual)
0                  Teff    372262.64     9.464053                   168918
1                  Oils    263073.00     6.688119                  2710189
2                  Beef    214032.00     5.441347                  2514743
3              Chat/Kat    213383.00     5.424847                      n/a
4                 Onion    196688.00     5.000409                   790646
5    Goat & mutton meat    166190.00     4.225057                  2705908
6                Coffee    163414.00     4.154483                 92101000
7               Berbere    154324.00     3.923387                   171319
8                 Sugar    147260.00     3.743799                   746784
9                 Maize    142614.64     3.625700                  2710826
10                 Rice    128899.50     3.277019                  2512381
11                Wheat    128603.45     3.269492                   169725
12       Pasta/Macaroni    111955.00     2.846238                  2708357
13               Tomato    107308.00     2.728097                  2709719
14        Bread/biscuit    104511.00     2.656989                  2707788
15                 Milk    104304.00     2.651726                   746782
16               Injera    102371.00     2.602583                  2707796
17               Potato     91536.00     2.327125                  2709382
18              Lentils     85598.00     2.176162                  2707425
19                Shiro     81285.00     2.066513              see non-fdc
20              Sorghum     58041.21     1.475585                   169716
21               Garlic     57442.00     1.460351                  2709786
22                 Soda     52734.00     1.340659                   174852
23         Leafy Greens     49082.00     1.247814                  2709578
24               Banana     47223.00     1.200553                  1105314
25                 Beer     46622.00     1.185274                   168746
26                 Eggs     44097.00     1.121080                  2707152
27          Butter/ghee     40524.00     1.030244                   171314
28                  Tea     40502.00     1.029684                  2710502
29                 Salt     37666.00     0.957585                   746775
30            Chick Pea     36370.00     0.924636                  2644282
31               Kariya     32802.00     0.833927                   170497
32           Horsebeans     30622.00     0.778505                  2707367
33              Poultry     22970.00     0.583968                  2646170
34               Orange     21841.00     0.555265                   746771
35               Barley     21452.25     0.545382                   170285
36                Mango     20986.00     0.533528                  2710834
37            Field Pea     20024.00     0.509071                  2644284
38  Other prepared food     16297.00     0.414319                      n/a
39               Carrot     15691.00     0.398913                  2258586
40            Fenugreek     13758.00     0.349770                   171324
41                Honey     11146.00     0.283365                   169640
42                 Fish     10506.00     0.267095                  2684445
43              Avocado     10272.00     0.261146                  2710824
44        Haricot Beans      9827.00     0.249832                  2346400
45                Kocho      9644.00     0.245180              See non-fdc
46             Beetroot      8938.00     0.227231                  2685576
47                Vetch      8621.00     0.219172                   170419
48               Millet      7587.00     0.192885                  2512379
49                 Oats      6414.25     0.163070                  2346397
50          Ground nuts      5900.00     0.149996                  2515376
51                Tella      5416.00     0.137691              See non-fdc
52               Cheese      4770.00     0.121268                   172179
53               Papaya      4562.00     0.115980                  2709246

In [149]:
inputstotal["FDC_ID_numeric"] = pd.to_numeric(inputstotal["FDC ID (blank if manual)"], errors='coerce')
inputstotalfiltered = inputstotal[inputstotal["FDC_ID_numeric"].notna()].drop(columns = ['FDC_ID_numeric'])
manual_items = inputstotal[~inputstotal["FDC_ID_numeric"].notna()].drop(columns = ['FDC_ID_numeric'])
inputstotalfiltered

            Food Items  Expenditure  % Total Exp FDC ID (blank if manual)
0                 Teff    372262.64     9.464053                   168918
1                 Oils    263073.00     6.688119                  2710189
2                 Beef    214032.00     5.441347                  2514743
4                Onion    196688.00     5.000409                   790646
5   Goat & mutton meat    166190.00     4.225057                  2705908
6               Coffee    163414.00     4.154483                 92101000
7              Berbere    154324.00     3.923387                   171319
8                Sugar    147260.00     3.743799                   746784
9                Maize    142614.64     3.625700                  2710826
10                Rice    128899.50     3.277019                  2512381
11               Wheat    128603.45     3.269492                   169725
12      Pasta/Macaroni    111955.00     2.846238                  2708357
13              Tomato    107308.00     2.728097                  2709719
14       Bread/biscuit    104511.00     2.656989                  2707788
15                Milk    104304.00     2.651726                   746782
16              Injera    102371.00     2.602583                  2707796
17              Potato     91536.00     2.327125                  2709382
18             Lentils     85598.00     2.176162                  2707425
20             Sorghum     58041.21     1.475585                   169716
21              Garlic     57442.00     1.460351                  2709786
22                Soda     52734.00     1.340659                   174852
23        Leafy Greens     49082.00     1.247814                  2709578
24              Banana     47223.00     1.200553                  1105314
25                Beer     46622.00     1.185274                   168746
26                Eggs     44097.00     1.121080                  2707152
27         Butter/ghee     40524.00     1.030244                   171314
28                 Tea     40502.00     1.029684                  2710502
29                Salt     37666.00     0.957585                   746775
30           Chick Pea     36370.00     0.924636                  2644282
31              Kariya     32802.00     0.833927                   170497
32          Horsebeans     30622.00     0.778505                  2707367
33             Poultry     22970.00     0.583968                  2646170
34              Orange     21841.00     0.555265                   746771
35              Barley     21452.25     0.545382                   170285
36               Mango     20986.00     0.533528                  2710834
37           Field Pea     20024.00     0.509071                  2644284
39              Carrot     15691.00     0.398913                  2258586
40           Fenugreek     13758.00     0.349770                   171324
41               Honey     11146.00     0.283365                   169640
42                Fish     10506.00     0.267095                  2684445
43             Avocado     10272.00     0.261146                  2710824
44       Haricot Beans      9827.00     0.249832                  2346400
46            Beetroot      8938.00     0.227231                  2685576
47               Vetch      8621.00     0.219172                   170419
48              Millet      7587.00     0.192885                  2512379
49                Oats      6414.25     0.163070                  2346397
50         Ground nuts      5900.00     0.149996                  2515376
52              Cheese      4770.00     0.121268                   172179
53              Papaya      4562.00     0.115980                  2709246

In [155]:
inputstotalfiltered.shape

(49, 4)

In [186]:
len(inputstotalfiltered['Food Items'])

49

In [187]:
inputstotalfiltered['Food Items']

0                   Teff
1                   Oils
2                   Beef
4                  Onion
5     Goat & mutton meat
6                 Coffee
7                Berbere
8                  Sugar
9                  Maize
10                  Rice
11                 Wheat
12        Pasta/Macaroni
13                Tomato
14         Bread/biscuit
15                  Milk
16                Injera
17                Potato
18               Lentils
20               Sorghum
21                Garlic
22                  Soda
23          Leafy Greens
24                Banana
25                  Beer
26                  Eggs
27           Butter/ghee
28                   Tea
29                  Salt
30             Chick Pea
31                Kariya
32            Horsebeans
33               Poultry
34                Orange
35                Barley
36                 Mango
37             Field Pea
39                Carrot
40             Fenugreek
41                 Honey
42                  Fish
43               Avocado
44         Haricot Beans
46              Beetroot
47                 Vetch
48                Millet
49                  Oats
50           Ground nuts
52                Cheese
53                Papaya
Name: Food Items, dtype: object

In [150]:
manual_items

             Food Items  Expenditure  % Total Exp FDC ID (blank if manual)
3              Chat/Kat     213383.0     5.424847                      n/a
19                Shiro      81285.0     2.066513              see non-fdc
38  Other prepared food      16297.0     0.414319                      n/a
45                Kocho       9644.0     0.245180              See non-fdc
51                Tella       5416.0     0.137691              See non-fdc

In [193]:
fullinput = inputstotalfiltered['FDC ID (blank if manual)']
completedf = createnutritiondfupdated(fullinput)
completedf.insert(0, 'Food Items',inputstotalfiltered['Food Items'].reset_index().drop(columns = ['index']))

Raw nutrient data:

/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal
/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal

In [196]:
get_nutrients(2707425)

/tmp/ipykernel_75/3216184753.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q["Energy"] = energy_kcal

Protein                                8.97000
Total lipid (fat)                      0.38000
Carbohydrate, by difference           20.00000
Energy                                27.48566
Alcohol, ethyl                         0.00000
                                        ...
PUFA 20:5 n-3 (EPA)                    0.00000
MUFA 22:1                              0.00000
PUFA 22:5 n-3 (DPA)                    0.00000
Fatty acids, total monounsaturated     0.06400
Fatty acids, total polyunsaturated     0.17400
Name: Quantity, Length: 65, dtype: float64

In [194]:
completedf

,Food Items,FDC_ID,Energy,Protein,Vitamin A,Vitamin D,Vitamin E,Vitamin C,Vitamin B-6,Vitamin B-12,...,Zinc,Fiber,Folate,Carbohydrate,Niacin,Phosphorus,Potassium,Riboflavin,Thiamin,Vitamin K
0,Teff,168918,0.329120,3.870000,0.0,NaN,NaN,NaN,0.09700,NaN,...,1.1100,2.8000,18.00,0.0,0.9090,120.00,107.00,0.0330,0.18300,NaN
1,Oils,2710189,0.701914,0.000000,0.0,NaN,NaN,0.0,0.00000,NaN,...,0.0000,0.0000,0.00,NaN,0.0000,0.00,0.00,0.0000,0.00000,NaN
2,Beef,2514743,190.134819,18.156250,NaN,NaN,NaN,NaN,NaN,NaN,...,4.1940,NaN,NaN,0.0,NaN,148.00,281.40,NaN,NaN,NaN
3,Onion,790646,0.124785,0.830000,NaN,NaN,NaN,8.2,NaN,NaN,...,0.2000,1.9000,NaN,0.0,NaN,34.00,182.00,NaN,NaN,NaN
4,Goat & mutton meat,2705908,0.110746,26.900000,0.0,NaN,NaN,0.0,0.00000,NaN,...,5.2300,0.0000,5.00,NaN,3.9200,199.00,402.00,0.6050,0.08900,NaN
5,Coffee,92101000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Berbere,171319,0.919508,13.460000,1483.0,NaN,NaN,0.7,2.09400,NaN,...,4.3000,34.8000,28.00,0.0,11.6000,300.00,1950.00,0.9400,0.25000,NaN
7,Sugar,746784,1.255647,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0100,NaN,NaN,0.0,NaN,0.00,2.00,NaN,NaN,NaN
8,Maize,2710826,72.857656,2.789375,NaN,NaN,NaN,NaN,0.15010,NaN,...,0.5564,2.4280,NaN,0.0,1.5930,75.46,237.00,0.1375,0.07875,NaN
9,Rice,2512381,369.637321,7.038850,NaN,NaN,NaN,NaN,0.05788,NaN,...,1.3540,0.1488,NaN,0.0,1.4340,108.20,82.26,0.0800,0.06500,NaN
10,Wheat,169725,0.645761,7.490000,0.0,NaN,NaN,2.6,0.26500,NaN,...,1.6500,1.1000,38.00,0.0,3.0870,200.00,169.00,0.1550,0.22500,NaN
11,Pasta/Macaroni,2708357,0.122445,5.760000,0.0,NaN,NaN,0.0,0.04900,NaN,...,0.5100,1.8000,73.00,NaN,1.6800,58.00,44.00,0.1350,0.27200,NaN
12,Tomato,2709719,0.015598,0.820000,32.0,NaN,NaN,16.3,0.07800,NaN,...,0.1500,1.2000,13.00,NaN,0.5970,23.00,226.00,0.0180,0.04600,NaN
13,Bread/biscuit,2707788,0.213694,10.700000,0.0,NaN,NaN,0.2,0.11100,NaN,...,1.0400,4.0000,85.00,NaN,5.5900,129.00,141.00,0.2520,0.41100,NaN
14,Milk,746782,0.195756,3.270000,32.0,NaN,NaN,NaN,0.06100,NaN,...,0.4200,NaN,0.00,0.0,0.1050,101.00,150.00,0.1380,0.05600,NaN
15,Injera,2707796,0.072531,2.550000,0.0,NaN,NaN,0.0,0.05100,NaN,...,0.5100,2.8000,29.00,NaN,1.1900,75.00,102.00,0.0690,0.13900,NaN
16,Potato,2709382,0.098268,1.870000,19.0,NaN,NaN,12.1,0.31200,NaN,...,0.2800,1.4000,9.00,NaN,1.3200,48.00,372.00,0.0200,0.10000,NaN
17,Lentils,2707425,0.089689,8.970000,0.0,NaN,NaN,1.4,0.16800,NaN,...,1.2600,7.9000,171.00,NaN,1.0000,179.00,367.00,0.0690,0.16000,NaN
18,Sorghum,169716,1.073929,10.620000,0.0,NaN,NaN,0.0,0.44300,NaN,...,1.6700,6.7000,20.00,0.0,3.6880,289.00,363.00,0.0960,0.33200,NaN
19,Garlic,2709786,0.111526,6.620000,0.0,NaN,NaN,10.0,1.24000,NaN,...,1.1600,2.7000,3.00,NaN,0.7000,153.00,401.00,0.1100,0.20000,NaN
20,Soda,174852,0.137263,0.000000,0.0,NaN,NaN,0.0,0.00000,NaN,...,0.0900,0.0000,0.00,0.0,0.0000,9.00,5.00,0.0000,0.00000,NaN
21,Leafy Greens,2709578,0.028077,2.960000,573.0,NaN,NaN,26.3,0.11400,NaN,...,0.2700,2.8000,76.00,NaN,0.6330,27.00,250.00,0.1150,0.04700,NaN
22,Banana,1105314,0.318201,0.740000,1.0,NaN,NaN,12.3,0.20900,NaN,...,0.1600,1.7000,14.00,0.0,0.6620,22.00,326.00,0.0000,0.05600,NaN
23,Beer,168746,0.141163,0.460000,0.0,NaN,NaN,0.0,0.04600,NaN,...,0.0100,0.0000,6.00,0.0,0.5130,14.00,27.00,0.0250,0.00500,NaN
24,Eggs,2707152,0.111526,12.400000,180.0,NaN,NaN,0.0,0.06300,NaN,...,1.2400,0.0000,71.00,NaN,0.0000,184.00,132.00,0.4190,0.07700,NaN
25,Butter/ghee,171314,2.937122,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,0.0000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
26,Tea,2710502,0.000780,0.000000,0.0,NaN,NaN,0.0,0.00000,NaN,...,0.0400,0.0000,1.00,NaN,0.0000,0.00,9.00,0.0040,0.01000,NaN
27,Salt,746775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,NaN,NaN,NaN,NaN,0.00,2.00,NaN,NaN,NaN
28,Chick Pea,2644282,371.994690,21.275000,NaN,NaN,NaN,NaN,NaN,NaN,...,3.1240,NaN,NaN,0.0,NaN,353.10,1074.00,NaN,NaN,NaN
29,Kariya,170497,0.130244,2.000000,59.0,NaN,NaN,242.5,0.27800,NaN,...,0.3000,1.5000,23.00,0.0,0.9500,46.00,340.00,0.0900,0.09000,NaN
30,Horsebeans,2707367,0.125565,7.060000,1.0,NaN,NaN,0.3,0.06400,NaN,...,0.9400,5.0000,92.00,NaN,0.6280,116.00,249.00,0.0790,0.08600,NaN
31,Poultry,2646170,112.202270,22.525000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6545,NaN,NaN,0.0,NaN,214.90,330.10,NaN,NaN,NaN
32,Orange,746771,0.152861,0.910000,NaN,NaN,NaN,59.1,0.07900,NaN,...,0.1100,2.0000,25.00,0.0,0.4250,23.00,166.00,0.0510,0.06800,NaN
33,Barley,170285,0.401651,2.260000,0.0,NaN,NaN,0.0,0.11500,NaN,...,0.8200,3.8000,16.00,0.0,2.0630,54.00,93.00,0.0620,0.08300,NaN
34,Mango,2710834,70.638801,0.687500,NaN,NaN,NaN,168.1,0.10810,NaN,...,0.1020,1.2890,NaN,0.0,NaN,17.74,204.40,NaN,NaN,NaN
35,Field Pea,2644284,345.570300,21.225000,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6540,NaN,NaN,0.0,NaN,427.60,1243.00,NaN,NaN,NaN
36,Carrot,2258586,44.978589,0.941250,NaN,NaN,NaN,NaN,0.14560,NaN,...,0.2364,3.0950,37.06,0.0,1.4060,39.81,279.60,0.0950,0.06500,NaN
37,Fenugreek,171324,1.054431,23.000000,3.0,NaN,NaN,3.0,0.60000,NaN,...,2.5000,24.6000,57.00,0.0,1.6400,296.00,770.00,0.3660,0.32200,NaN
38,Honey,169640,0.992039,0.300000,0.0,NaN,NaN,0.5,0.02400,NaN,...,0.2200,0.2000,2.00,0.0,0.1210,4.00,52.00,0.0380,0.00000,NaN
39,Fish,2684445,133.787497,16.468750,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4749,NaN,NaN,0.0,NaN,166.20,292.30,NaN,NaN,NaN
40,Avocado,2710824,206.049300,1.812500,NaN,NaN,NaN,0.0,0.16740,NaN,...,0.4596,NaN,128.70,0.0,NaN,42.38,576.40,NaN,NaN,NaN
41,Haricot Beans,2346400,33.567946,1.968750,NaN,NaN,NaN,NaN,0.12100,NaN,...,0.3498,3.0110,NaN,0.0,0.7313,41.15,290.40,NaN,0.06000,NaN
42,Beetroot,2685576,40.965255,1.687500,NaN,NaN,NaN,NaN,NaN,NaN,...,0.3104,3.1190,NaN,0.0,NaN,33.65,341.50,NaN,NaN,NaN
43,Vetch,170419,0.264388,5.420000,38.0,NaN,NaN,40.0,0.16900,NaN,...,1.2400,5.7000,65.00,0.0,2.0900,108.00,244.00,0.1320,0.26600,NaN
44,Millet,2512379,380.606497,10.021770,NaN,NaN,NaN,NaN,0.19180,NaN,...,2.2580,2.6190,NaN,0.0,4.8600,257.90,214.10,0.1363,0.41130,NaN
45,Oats,2346397,379.208061,12.511180,NaN,NaN,NaN,NaN,0.11890,NaN,...,2.8430,NaN,29.99,0.0,0.9263,417.30,375.90,NaN,0.33380,NaN
46,Ground nuts,2515376,550.621810,23.205000,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7800,8.0140,NaN,0.0,NaN,380.40,635.60,NaN,NaN,NaN
47,Cheese,172179,0.321321,11.120000,37.0,NaN,NaN,0.0,0.04600,NaN,...,0.4000,0.0000,12.00,0.0,0.0990,159.00,104.00,0.1630,0.02700,NaN
48,Papaya,2709246,0.033536,0.470000,47.0,NaN,NaN,60.9,0.03800,NaN,...,0.0800,1.7000,37.00,NaN,0.3570,10.00,182.00,0.0270,0.02300,NaN

In [122]:
completedf.to_pickle('nutrient_info.pkl')

In [22]:
all_nutrients = []  # list to store each food's nutrient Series

for i, row in dfmanualitems.iterrows():
    fdc_code = row['FDC code or source']
    
    # Only proceed if there is a valid FDC code
    if pd.notnull(fdc_code) and isinstance(fdc_code, int):
        # Call your function that returns a Series of nutrients
        s = get_nutrients(fdc_code)
        
        # Name the Series after the ingredient so it becomes the row name
        s.name = row['ingredient']
        
        # Collect it in our list
        all_nutrients.append(s)

# Combine all nutrient Series into one DataFrame
df_nutrients = pd.concat(all_nutrients, axis=1).T

# Fill missing nutrients with 0
df_nutrients = df_nutrients.fillna(0)

df_nutrients.head()

,Proximates,Water,Energy (Atwater General Factors),Energy (Atwater Specific Factors),Nitrogen,Protein,Total lipid (fat),Ash,Carbohydrates,"Carbohydrate, by difference",...,Energy,"Molybdenum, Mo",Total dietary fiber (AOAC 2011.25),High Molecular Weight Dietary Fiber (HMWDF),Low Molecular Weight Dietary Fiber (LMWDF),Beta-glucan,"Sulfur, S","Nickel, Ni","Cobalt, Co","Boron, B"
Lentils,0.0,9.451,360.2850,350.932800,3.7710,23.568750,1.925,2.8840,0.0,62.171250,...,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Tomato,0.0,94.730,21.9574,18.954361,0.1113,0.695625,0.425,0.3119,0.0,3.837475,...,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Wheat,0.0,9.440,0.0000,0.000000,2.4100,15.100000,2.730,1.5600,0.0,71.200000,...,1550.0,58.50,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Chick Pea,0.0,8.774,382.9980,371.994690,3.4040,21.275000,6.274,3.3190,0.0,60.358000,...,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
PoultryMillet,0.0,10.210,375.6180,380.606497,1.7190,10.021770,4.194,1.1280,0.0,74.446230,...,0.0,29.54,3.326,2.729,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
columnsnut = ['Proximates', 'Water', 'Energy (Atwater General Factors)',
       'Energy (Atwater Specific Factors)', 'Nitrogen', 'Protein',
       'Total lipid (fat)', 'Ash', 'Carbohydrates',
       'Carbohydrate, by difference', 'Starch', 'Minerals', 'Calcium, Ca',
       'Iron, Fe', 'Magnesium, Mg', 'Phosphorus, P', 'Potassium, K',
       'Sodium, Na', 'Zinc, Zn', 'Copper, Cu', 'Manganese, Mn',
       'Fiber, total dietary', 'Selenium, Se', 'Vitamins and Other Components',
       'Vitamin C, total ascorbic acid', 'Thiamin', 'Riboflavin', 'Niacin',
       'Vitamin B-6', 'Biotin', 'Folate, total', 'Vitamin A, RAE',
       'Carotene, beta', 'Carotene, alpha', 'Carotene, gamma',
       'Cryptoxanthin, beta', 'Cryptoxanthin, alpha', 'Lycopene',
       'Lutein + zeaxanthin', 'cis-Lutein/Zeaxanthin', 'Lutein', 'Zeaxanthin',
       'Energy', 'Molybdenum, Mo', 'Total dietary fiber (AOAC 2011.25)',
       'High Molecular Weight Dietary Fiber (HMWDF)',
       'Low Molecular Weight Dietary Fiber (LMWDF)', 'Beta-glucan',
       'Sulfur, S', 'Nickel, Ni', 'Cobalt, Co', 'Boron, B']

In [28]:
#didnt add all properly so here goes
def add_new_series(inputdf, fdcid):
    new_nutrients = get_nutrients(fdcid)
    new_series = new_nutrients.reindex(df_nutrients.columns, fill_value=0)
    inputdf.loc[new_series.name] = new_series
    return inputdf

In [24]:
# add our carrot, pea, and haricot beans
updateddf = (df_nutrients.pipe(add_new_series,2258586).pipe(add_new_series,2644291).pipe(add_new_series,747441))
updateddf

,Proximates,Water,Energy (Atwater General Factors),Energy (Atwater Specific Factors),Nitrogen,Protein,Total lipid (fat),Ash,Carbohydrates,"Carbohydrate, by difference",...,Energy,"Molybdenum, Mo",Total dietary fiber (AOAC 2011.25),High Molecular Weight Dietary Fiber (HMWDF),Low Molecular Weight Dietary Fiber (LMWDF),Beta-glucan,"Sulfur, S","Nickel, Ni","Cobalt, Co","Boron, B"
Lentils,0.0,9.451,360.2850,350.932800,3.7710,23.568750,1.9250,2.8840,0.0,62.171250,...,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Tomato,0.0,94.730,21.9574,18.954361,0.1113,0.695625,0.4250,0.3119,0.0,3.837475,...,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Wheat,0.0,9.440,0.0000,0.000000,2.4100,15.100000,2.7300,1.5600,0.0,71.200000,...,1550.0,58.50,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Chick Pea,0.0,8.774,382.9980,371.994690,3.4040,21.275000,6.2740,3.3190,0.0,60.358000,...,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
PoultryMillet,0.0,10.210,375.6180,380.606497,1.7190,10.021770,4.1940,1.1280,0.0,74.446230,...,0.0,29.54,3.326,2.729,0.0,0.0,0.0,0.0,0.0,0.0
Carrot,0.0,87.720,47.9906,44.978589,0.1506,0.941250,0.3506,0.7206,0.0,10.267550,...,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Field Pea,0.0,80.530,80.1450,77.798925,0.7575,4.734375,1.1530,0.8750,0.0,12.707625,...,0.0,0.00,5.950,0.000,0.0,0.0,0.0,0.0,0.0,0.0
Haricot Beans,0.0,0.000,0.0000,0.000000,0.0000,24.100000,1.5100,0.0000,0.0,0.000000,...,0.0,840.00,0.000,0.000,0.0,0.0,244.0,220.0,38.9,1220.0

In [40]:
def createnutritiondf(fdcids):
    outputdf = pd.DataFrame(columns = columnsnut)
    for fdcid in fdcids:
        outputdf = add_new_series(outputdf,fdcid)
    selected_items = [
    'Energy', 'Protein', 'Vitamin A', 'Vitamin D', 'Vitamin E', 'Vitamin C',
    'Vitamin B-6', 'Vitamin B-12', 'Calcium', 'Magnesium', 'Iron', 'Zinc',
    'Fiber', 'Folate', 'Carbohydrate', 'Niacin', 'Phosphorus', 'Potassium',
    'Riboflavin', 'Thiamin', 'Vitamin K'
]
    
    # A dictionary mapping your selected item -> the "best match" current column
    # (where a reasonable match exists in your current columns)
    best_match_map = {
        'Energy': 'Energy (Atwater Specific Factors)',  # or "Energy (Atwater General Factors)" if you prefer
        'Protein': 'Protein',
        'Vitamin A': 'Vitamin A, RAE',
        'Vitamin C': 'Vitamin C, total ascorbic acid',
        'Vitamin B-6': 'Vitamin B-6',
        'Calcium': 'Calcium, Ca',
        'Magnesium': 'Magnesium, Mg',
        'Iron': 'Iron, Fe',
        'Zinc': 'Zinc, Zn',
        'Fiber': 'Fiber, total dietary',  # or "Total dietary fiber (AOAC 2011.25)"
        'Folate': 'Folate, total',
        'Carbohydrate': 'Carbohydrates',  # or "Carbohydrate, by difference"
        'Niacin': 'Niacin',
        'Phosphorus': 'Phosphorus, P',
        'Potassium': 'Potassium, K',
        'Riboflavin': 'Riboflavin',
        'Thiamin': 'Thiamin'
        # Note: Vitamin D, Vitamin E, Vitamin B-12, Vitamin K have no direct match
    }
    
    # 1) Identify which of your selected items can be matched vs. not matched
    matched_items = [item for item in selected_items if item in best_match_map]
    unmatched_items = [item for item in selected_items if item not in best_match_map]
    
    # 2) From your dataframe, select the matched columns (if they exist in df)
    #    and rename them from current name -> selected item name.
    #    We'll assume your dataframe is named df.
    cols_to_select = [best_match_map[item] for item in matched_items]
    df_matched = updateddf[cols_to_select].rename(columns={best_match_map[item]: item for item in matched_items})
    
    # 3) For unmatched selected items, create empty columns (NaN) so that
    #    you still end up with all selected items in the final dataframe.
    for item in unmatched_items:
        df_matched[item] = np.nan
    
    # 4) Reorder columns to match exactly your selected_items list
    df_final = df_matched[selected_items]
    
    # Now df_final contains only your selected nutrients in the correct order.
    resetedfinal = df_final.reset_index()
    return resetedfinal

In [41]:
inputs = [2644283, 1999634, 790085, 2644282, 2512379, 2258586]

In [46]:
createnutritiondfupdated(inputs)

,index,Energy,Protein,Vitamin A,Vitamin D,Vitamin E,Vitamin C,Vitamin B-6,Vitamin B-12,Calcium,...,Zinc,Fiber,Folate,Carbohydrate,Niacin,Phosphorus,Potassium,Riboflavin,Thiamin,Vitamin K
0,Lentils,0.0,23.568750,0.0,NaN,NaN,0.00,0.00000,NaN,61.850,...,3.86300,0.0000,0.000,0.0,0.0000,373.60,948.9,0.0000,0.00000,NaN
1,Tomato,0.0,0.695625,23.9,NaN,NaN,17.75,0.07894,NaN,9.963,...,0.08245,0.9706,9.994,0.0,0.5331,19.09,192.8,0.0000,0.05575,NaN
2,Wheat,1550.0,15.100000,0.0,NaN,NaN,0.00,0.26800,NaN,38.000,...,3.24000,10.6000,39.000,0.0,5.5500,352.00,376.0,0.1280,0.50400,NaN
3,Chick Pea,0.0,21.275000,0.0,NaN,NaN,0.00,0.00000,NaN,111.100,...,3.12400,0.0000,0.000,0.0,0.0000,353.10,1074.0,0.0000,0.00000,NaN
4,PoultryMillet,0.0,10.021770,0.0,NaN,NaN,0.00,0.19180,NaN,9.105,...,2.25800,2.6190,0.000,0.0,4.8600,257.90,214.1,0.1363,0.41130,NaN
5,Carrot,0.0,0.941250,0.0,NaN,NaN,0.00,0.14560,NaN,30.480,...,0.23640,3.0950,37.060,0.0,1.4060,39.81,279.6,0.0950,0.06500,NaN
6,Field Pea,0.0,4.734375,0.0,NaN,NaN,0.00,0.00000,NaN,28.210,...,0.71200,0.0000,0.000,0.0,0.0000,77.74,109.2,0.0000,0.00000,NaN
7,Haricot Beans,0.0,24.100000,0.0,NaN,NaN,0.00,0.00000,NaN,229.000,...,3.31000,4.3000,0.000,0.0,0.0000,523.00,1470.0,0.0000,0.00000,NaN

In [45]:
# Helper function: Returns the first candidate found in the available columns
def get_preferred_column(candidates, available_columns):
    for candidate in candidates:
        if candidate in available_columns:
            return candidate
    return None

def createnutritiondfupdated(fdcids):
    outputdf = pd.DataFrame(columns=columnsnut)  # Assume columnsnut is defined elsewhere
    for fdcid in fdcids:
        outputdf = add_new_series(outputdf, fdcid)  # Your function for adding food data
    
    # Define the list of nutrients that you want in your final DataFrame
    selected_items = [
        'Energy', 'Protein', 'Vitamin A', 'Vitamin D', 'Vitamin E', 'Vitamin C',
        'Vitamin B-6', 'Vitamin B-12', 'Calcium', 'Magnesium', 'Iron', 'Zinc',
        'Fiber', 'Folate', 'Carbohydrate', 'Niacin', 'Phosphorus', 'Potassium',
        'Riboflavin', 'Thiamin', 'Vitamin K'
    ]

    # Create a dictionary where each nutrient maps to a list of candidate columns (by priority)
    # For nutrients not needing hierarchy, a single element list is enough.
    priority_map = {
        'Energy': ["Energy", "Energy (Atwater Specific Factors)", "Energy (Atwater General Factors)"],
        'Protein': ["Protein"],
        'Vitamin A': ["Vitamin A, RAE"],
        'Vitamin C': ["Vitamin C, total ascorbic acid"],
        'Vitamin B-6': ["Vitamin B-6"],
        'Calcium': ["Calcium, Ca"],
        'Magnesium': ["Magnesium, Mg"],
        'Iron': ["Iron, Fe"],
        'Zinc': ["Zinc, Zn"],
        'Fiber': ["Fiber, total dietary"],
        'Folate': ["Folate, total"],
        'Carbohydrate': ["Carbohydrates"],  # or you might include "Carbohydrate, by difference" as a candidate
        'Niacin': ["Niacin"],
        'Phosphorus': ["Phosphorus, P"],
        'Potassium': ["Potassium, K"],
        'Riboflavin': ["Riboflavin"],
        'Thiamin': ["Thiamin"],
        # For nutrients without clear mapping, leave as an empty list or don't include them
        # 'Vitamin D': [], 'Vitamin E': [], 'Vitamin B-12': [], 'Vitamin K': []
    }
    
    # Build the best_match_map based on what columns are available in your DataFrame (here, updateddf)
    best_match_map = {}
    for nutrient, candidates in priority_map.items():
        match = get_preferred_column(candidates, updateddf.columns)
        if match is not None:
            best_match_map[nutrient] = match

    # Separate selected items into those with a mapping and those without a mapping
    matched_items = [item for item in selected_items if item in best_match_map]
    unmatched_items = [item for item in selected_items if item not in best_match_map]
    
    # Select the matched columns from updateddf and rename them to the selected item names
    cols_to_select = [best_match_map[item] for item in matched_items]
    df_matched = updateddf[cols_to_select].rename(columns={best_match_map[item]: item for item in matched_items})
    
    # For unmatched items, create empty columns (NaN)
    for item in unmatched_items:
        df_matched[item] = np.nan
    
    # Reorder the columns to match exactly the list of selected items
    df_final = df_matched[selected_items]
    
    return df_final.reset_index()

# Example usage:
# final_df = createnutritiondf(list_of_fdcids)

In [25]:
updateddf.columns

Index(['Proximates', 'Water', 'Energy (Atwater General Factors)',
       'Energy (Atwater Specific Factors)', 'Nitrogen', 'Protein',
       'Total lipid (fat)', 'Ash', 'Carbohydrates',
       'Carbohydrate, by difference', 'Starch', 'Minerals', 'Calcium, Ca',
       'Iron, Fe', 'Magnesium, Mg', 'Phosphorus, P', 'Potassium, K',
       'Sodium, Na', 'Zinc, Zn', 'Copper, Cu', 'Manganese, Mn',
       'Fiber, total dietary', 'Selenium, Se', 'Vitamins and Other Components',
       'Vitamin C, total ascorbic acid', 'Thiamin', 'Riboflavin', 'Niacin',
       'Vitamin B-6', 'Biotin', 'Folate, total', 'Vitamin A, RAE',
       'Carotene, beta', 'Carotene, alpha', 'Carotene, gamma',
       'Cryptoxanthin, beta', 'Cryptoxanthin, alpha', 'Lycopene',
       'Lutein + zeaxanthin', 'cis-Lutein/Zeaxanthin', 'Lutein', 'Zeaxanthin',
       'Energy', 'Molybdenum, Mo', 'Total dietary fiber (AOAC 2011.25)',
       'High Molecular Weight Dietary Fiber (HMWDF)',
       'Low Molecular Weight Dietary Fiber (LMWDF)', 'Beta-glucan',
       'Sulfur, S', 'Nickel, Ni', 'Cobalt, Co', 'Boron, B'],
      dtype='object')

## Time to map the nutrients properly

In [26]:
import numpy as np

# Your selected items:
selected_items = [
    'Energy', 'Protein', 'Vitamin A', 'Vitamin D', 'Vitamin E', 'Vitamin C',
    'Vitamin B-6', 'Vitamin B-12', 'Calcium', 'Magnesium', 'Iron', 'Zinc',
    'Fiber', 'Folate', 'Carbohydrate', 'Niacin', 'Phosphorus', 'Potassium',
    'Riboflavin', 'Thiamin', 'Vitamin K'
]

# A dictionary mapping your selected item -> the "best match" current column
# (where a reasonable match exists in your current columns)
best_match_map = {
    'Energy': 'Energy',  # or "Energy (Atwater General Factors)" if you prefer
    'Protein': 'Protein',
    'Vitamin A': 'Vitamin A, RAE',
    'Vitamin C': 'Vitamin C, total ascorbic acid',
    'Vitamin B-6': 'Vitamin B-6',
    'Calcium': 'Calcium, Ca',
    'Magnesium': 'Magnesium, Mg',
    'Iron': 'Iron, Fe',
    'Zinc': 'Zinc, Zn',
    'Fiber': 'Fiber, total dietary',  # or "Total dietary fiber (AOAC 2011.25)"
    'Folate': 'Folate, total',
    'Carbohydrate': 'Carbohydrates',  # or "Carbohydrate, by difference"
    'Niacin': 'Niacin',
    'Phosphorus': 'Phosphorus, P',
    'Potassium': 'Potassium, K',
    'Riboflavin': 'Riboflavin',
    'Thiamin': 'Thiamin'
    # Note: Vitamin D, Vitamin E, Vitamin B-12, Vitamin K have no direct match
}

# 1) Identify which of your selected items can be matched vs. not matched
matched_items = [item for item in selected_items if item in best_match_map]
unmatched_items = [item for item in selected_items if item not in best_match_map]

# 2) From your dataframe, select the matched columns (if they exist in df)
#    and rename them from current name -> selected item name.
#    We'll assume your dataframe is named df.
cols_to_select = [best_match_map[item] for item in matched_items]
df_matched = updateddf[cols_to_select].rename(columns={best_match_map[item]: item for item in matched_items})

# 3) For unmatched selected items, create empty columns (NaN) so that
#    you still end up with all selected items in the final dataframe.
for item in unmatched_items:
    df_matched[item] = np.nan

# 4) Reorder columns to match exactly your selected_items list
df_final = df_matched[selected_items]

# Now df_final contains only your selected nutrients in the correct order.
resetedfinal = df_final.reset_index()
resetedfinal

,index,Energy,Protein,Vitamin A,Vitamin D,Vitamin E,Vitamin C,Vitamin B-6,Vitamin B-12,Calcium,...,Zinc,Fiber,Folate,Carbohydrate,Niacin,Phosphorus,Potassium,Riboflavin,Thiamin,Vitamin K
0,Lentils,0.0,23.568750,0.0,NaN,NaN,0.00,0.00000,NaN,61.850,...,3.86300,0.0000,0.000,0.0,0.0000,373.60,948.9,0.0000,0.00000,NaN
1,Tomato,0.0,0.695625,23.9,NaN,NaN,17.75,0.07894,NaN,9.963,...,0.08245,0.9706,9.994,0.0,0.5331,19.09,192.8,0.0000,0.05575,NaN
2,Wheat,1550.0,15.100000,0.0,NaN,NaN,0.00,0.26800,NaN,38.000,...,3.24000,10.6000,39.000,0.0,5.5500,352.00,376.0,0.1280,0.50400,NaN
3,Chick Pea,0.0,21.275000,0.0,NaN,NaN,0.00,0.00000,NaN,111.100,...,3.12400,0.0000,0.000,0.0,0.0000,353.10,1074.0,0.0000,0.00000,NaN
4,PoultryMillet,0.0,10.021770,0.0,NaN,NaN,0.00,0.19180,NaN,9.105,...,2.25800,2.6190,0.000,0.0,4.8600,257.90,214.1,0.1363,0.41130,NaN
5,Carrot,0.0,0.941250,0.0,NaN,NaN,0.00,0.14560,NaN,30.480,...,0.23640,3.0950,37.060,0.0,1.4060,39.81,279.6,0.0950,0.06500,NaN
6,Field Pea,0.0,4.734375,0.0,NaN,NaN,0.00,0.00000,NaN,28.210,...,0.71200,0.0000,0.000,0.0,0.0000,77.74,109.2,0.0000,0.00000,NaN
7,Haricot Beans,0.0,24.100000,0.0,NaN,NaN,0.00,0.00000,NaN,229.000,...,3.31000,4.3000,0.000,0.0,0.0000,523.00,1470.0,0.0000,0.00000,NaN

In [27]:
ready_to_stack = resetedfinal.reindex(columns=matched_ing.columns)
cumulativedf = pd.concat([resetedfinal, matched_ing], axis=0, ignore_index=True).fillna(0)
#need to fix energy values for some reason so i'll manually fill
cumulativedf.iloc[0, 1] = 
cumulativedf

SyntaxError: invalid syntax (675121741.py, line 4)

# Time for manual input from other sources

In [ ]:
import ipywidgets as widgets
from IPython.display import display

selected_nutrients = [
    'Energy', 'Protein', 'Vitamin A', 'Vitamin D', 'Vitamin E', 'Vitamin C',
    'Vitamin B-6', 'Vitamin B-12', 'Calcium', 'Magnesium', 'Iron', 'Zinc',
    'Fiber', 'Folate', 'Carbohydrate', 'Niacin', 'Phosphorus', 'Potassium',
    'Riboflavin', 'Thiamin', 'Vitamin K'
]

manualinputs = pd.DataFrame(columns=['Food Name'] + selected_nutrients)

# create a text widget for the food name
food_name_input = widgets.Text(
    value='',
    placeholder='Enter food name',
    description='Food Name:'
)

# create FloatText widgets for each nutrient
nutrient_widgets = {}
for nutrient in selected_nutrients:
    nutrient_widgets[nutrient] = widgets.FloatText(
        value=0.0,
        description=nutrient,
        style={'description_width': 'initial'}  # so the label doesn't get cut off
    )

submit_button = widgets.Button(
    description='Submit',
    button_style='success'  # 'success', 'info', 'warning', 'danger' or ''
)

def on_submit_clicked(b):
    # build a dictionary for the new row
    new_entry = {}
    new_entry['Food Name'] = food_name_input.value
    
    for nutrient in selected_nutrients:
        new_entry[nutrient] = nutrient_widgets[nutrient].value
    
    new_row_df = pd.DataFrame([new_entry])
    
    # Append to global df manualinputs
    global manualinputs
    manualinputs = pd.concat([manualinputs, new_row_df], ignore_index=True)
    
    print("New entry added!")
    display(manualinputs.tail())

submit_button.on_click(on_submit_clicked)

nutrient_box = widgets.VBox(list(nutrient_widgets.values()))
ui = widgets.VBox([food_name_input, nutrient_box, submit_button])
display(ui)

In [ ]:
manualinputs

In [107]:
#save as pickle
df.to_pickle("global_df.pkl")

In [127]:
loadmatched['ingredient'][loadmatched['best_match'] == np.nan]

Series([], Name: ingredient, dtype: object)

In [128]:
num_matches = loadmatched.count()

In [125]:
matched_df = matched1r.merge(
    nutrient_df, 
    how="left",  # or "inner" if you only want rows that definitely match
    left_on="best_match", 
    right_on="Ingredient description"
)
matched_df.iloc[[0,5,11,12,14]].drop(columns = ['best_match', 'justification'])

,ingredient,ingred_code,Ingredient description,Capric acid,Lauric acid,Myristic acid,Palmitic acid,Palmitoleic acid,Stearic acid,Oleic acid,...,Vitamin B12,"Vitamin B-12, added",Vitamin B6,Vitamin C,Vitamin D,Vitamin E,"Vitamin E, added",Vitamin K,Water,Zinc
0,Lentils,16069.0,"Lentils, raw",0.000,0.000,0.003,0.136,0.003,0.015,0.184,...,0.0,0.0,0.540,4.5,0.0,0.49,0.0,5.0,8.26,3.27
5,Carrot,11124.0,"Carrots, raw",0.000,0.000,0.000,0.035,0.002,0.002,0.012,...,0.0,0.0,0.138,5.9,0.0,0.66,0.0,13.2,88.29,0.24
11,Other condiments,2009.0,"Spices, chili powder",0.013,0.081,0.189,1.619,0.082,0.396,3.116,...,0.0,0.0,2.094,0.7,0.0,38.14,0.0,105.7,10.75,4.30
12,Other seed,12220.0,"Seeds, flaxseed",0.000,0.000,0.008,2.165,0.024,1.330,7.359,...,0.0,0.0,0.473,0.6,0.0,0.31,0.0,4.3,6.96,4.34
14,Other tuber or stem,11141.0,"Celeriac, raw",0.000,0.000,0.002,0.069,0.002,0.006,0.056,...,0.0,0.0,0.165,8.0,0.0,0.36,0.0,41.0,88.00,0.33

In [124]:
nutrient_df = read_sheets(Ethiopia_Data,sheet='rdas')
nutrient_df

,ingred_code,Ingredient description,Capric acid,Lauric acid,Myristic acid,Palmitic acid,Palmitoleic acid,Stearic acid,Oleic acid,Linoleic Acid,...,Vitamin B12,"Vitamin B-12, added",Vitamin B6,Vitamin C,Vitamin D,Vitamin E,"Vitamin E, added",Vitamin K,Water,Zinc
0,1001,"Butter, salted",2.529,2.587,7.436,21.697,0.961,9.999,19.961,2.728,...,0.17,0.0,0.003,0.0,0.0,2.32,0.0,7.0,15.87,0.09
1,1002,"Butter, whipped, with salt",2.039,2.354,7.515,20.531,1.417,7.649,17.370,2.713,...,0.07,0.0,0.008,0.0,0.0,1.37,0.0,4.6,16.72,0.05
2,1003,"Butter oil, anhydrous",2.495,2.793,10.005,26.166,2.228,12.056,25.026,2.247,...,0.01,0.0,0.001,0.0,0.0,2.80,0.0,8.6,0.24,0.01
3,1004,"Cheese, blue",0.601,0.491,3.301,9.153,0.816,3.235,6.622,0.536,...,1.22,0.0,0.166,0.0,0.5,0.25,0.0,2.4,42.41,2.66
4,1005,"Cheese, brick",0.585,0.482,3.227,8.655,0.817,3.455,7.401,0.491,...,1.26,0.0,0.065,0.0,0.5,0.26,0.0,2.5,41.11,2.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2745,19312,"Pie fillings, apple, canned",0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.00,0.0,0.016,1.7,0.0,0.04,0.0,0.5,73.40,0.04
2746,21610,"School Lunch, chicken patty, whole grain breaded",0.000,0.000,0.000,2.162,0.361,0.481,4.035,6.419,...,0.31,0.0,0.195,0.7,0.3,1.36,0.0,4.9,53.84,1.12
2747,23090,"Beef, chuck for stew, separable lean and fat, ...",0.000,0.000,0.173,1.546,0.238,0.989,3.146,0.366,...,2.73,0.0,0.511,0.0,0.1,0.11,0.0,1.6,60.08,8.32
2748,43449,"Beans, baked, canned, no salt added",0.000,0.000,0.000,0.097,0.000,0.006,0.035,0.093,...,0.00,0.0,0.130,3.1,0.0,0.15,0.0,0.8,72.60,1.40
2749,100173,"Sausage, pork, chorizo, link or ground, cooked...",0.020,0.022,0.346,5.900,0.573,3.000,10.890,4.180,...,1.21,0.0,0.554,0.0,1.5,1.50,0.0,6.0,46.30,2.19

In [123]:
#connect non None best matches to their nutrition info
matched1r = leftover1stround[~leftover1stround['best_match'].isna()]
matched1r

,ingredient,best_match,justification
8,Lentils,"Lentils, raw",Exact match for raw lentils.
18,Tomato,"Tomatoes, raw",Exact match for raw tomatoes.
20,Wheat,"Wheat, hard white, raw",Exact match for raw wheat.
25,Chick Pea,"Chickpeas, raw",Exact match for raw chickpeas.
32,Poultry,"Chicken, broilers or fryers, roasted, meat and...",Chicken is a type of poultry.
36,Carrot,"Carrots, raw",Exact match for raw carrots.
38,Other prepared food,"Soup, chicken, low sodium, canned, condensed",Canned soup is a prepared food.
40,Mung bean,"Mung beans, raw",Exact match for raw mung beans.
46,Other fruit,"Fruit salad, (peach and pear and apricot and p...",Fruit salad comprises various fruits.
49,Sesame,"Seeds, sesame seeds, whole, roasted and toasted",Closest match for sesame seeds.
54,Sun Flower,"Sunflower seeds, dry roasted, without salt",Sunflower refers to sunflower seeds.
57,Other condiments,"Spices, chili powder",Chili powder is a type of condiment.
60,Other seed,"Seeds, flaxseed",Flaxseed is a type of seed.
61,Haricot Beans,"Beans, navy, mature seeds, raw",Haricot beans are also known as navy beans.
66,Other tuber or stem,"Celeriac, raw",Celeriac is an uncommon tuber-like plant.

In [122]:
leftover1stround = loadmatched[mask]
leftover1stround #rows taken by chat

,ingredient,best_match,justification
3,Shiro,None,"No good match for Shiro, a traditional Ethiopi..."
6,Kariya,None,"No good match for Kariya, potentially a local ..."
8,Lentils,"Lentils, raw",Exact match for raw lentils.
18,Tomato,"Tomatoes, raw",Exact match for raw tomatoes.
19,Horsebeans,None,No good match for horsebeans (broad beans).
20,Wheat,"Wheat, hard white, raw",Exact match for raw wheat.
25,Chick Pea,"Chickpeas, raw",Exact match for raw chickpeas.
30,Hops (gesho),None,"No good match for gesho, a traditional Ethiopi..."
32,Poultry,"Chicken, broilers or fryers, roasted, meat and...",Chicken is a type of poultry.
35,Millet,None,"No good match for millet, a small-seeded grain."
36,Carrot,"Carrots, raw",Exact match for raw carrots.
37,Field Pea,None,No good match found for field peas.
38,Other prepared food,"Soup, chicken, low sodium, canned, condensed",Canned soup is a prepared food.
40,Mung bean,"Mung beans, raw",Exact match for raw mung beans.
44,Vetch,None,"No good match for vetch, a type of legume."
46,Other fruit,"Fruit salad, (peach and pear and apricot and p...",Fruit salad comprises various fruits.
49,Sesame,"Seeds, sesame seeds, whole, roasted and toasted",Closest match for sesame seeds.
54,Sun Flower,"Sunflower seeds, dry roasted, without salt",Sunflower refers to sunflower seeds.
57,Other condiments,"Spices, chili powder",Chili powder is a type of condiment.
58,Niger Seed,None,"No good match for niger seed, typically used f..."
60,Other seed,"Seeds, flaxseed",Flaxseed is a type of seed.
61,Haricot Beans,"Beans, navy, mature seeds, raw",Haricot beans are also known as navy beans.
63,Chat/Kat,None,"No good match for Chat or Kat, a stimulant plant."
64,Bula,None,"No good match for Bula, potentially a local term."
66,Other tuber or stem,"Celeriac, raw",Celeriac is an uncommon tuber-like plant.
68,Kocho,None,"No good match for Kocho, a traditional Ethiopi..."
70,Godere,None,"No good match for Godere, a type of tuber."

In [120]:
pd.reset_option('display.max_rows')

In [121]:
mask = ~loadmatched['ingredient'].isin(matched_ing['index'])
loadmatched[mask].shape[0] #rows taken up by chat to classify

27